import Talent from "@/types/Talent";

const talents_test_data: Talent[] = [
  {
    name: "Juan Lopez Martinez",
    role: "Full-stack developer",
    rating: 3,
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
  {
    name: "Claudia Castillo",
    role: "Full-stack developer",
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
  {
    name: "Jorge Ramirez",
    role: "Full-stack developer",
    rating: 1,
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
  {
    name: "Claudia Castillo",
    role: "Full-stack developer",
    rating: 4,
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
  {
    name: "Jorge Ramirez",
    role: "Full-stack developer",
    rating: 1,
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
  {
    name: "Jorge Ramirez",
    role: "Full-stack developer",
    rating: 1,
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
  {
    name: "Claudia Castillo",
    role: "Full-stack developer",
    rating: 4,
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
  {
    name: "Jorge Ramirez",
    role: "Full-stack developer",
    rating: 1,
    city: "Lima",
    country: "Perú",
    salary_min: 2500,
    salary_max: 3000,
  },
];

export default talents_test_data;
